const OFFICIAL_SOURCES = {
  utilityGuide: {
    title: "USPTO: Applying for a utility patent",
    href: "https://www.uspto.gov/patents/basics/apply/utility-patent",
    note: "Official overview of the U.S. utility-patent application process.",
  },
  mpep608: {
    title: "MPEP § 608: Disclosure",
    href: "https://www.uspto.gov/web/offices/pac/mpep/s608.html",
    note: "USPTO examination guidance concerning the specification, drawings, claims, and abstract.",
  },
  mpep707: {
    title: "MPEP § 707: Examiner's Letter or Action",
    href: "https://www.uspto.gov/web/offices/pac/mpep/s707.html",
    note: "USPTO examination guidance concerning Office actions and claim treatment.",
  },
  mpep2163: {
    title: "MPEP § 2163: Written Description",
    href: "https://www.uspto.gov/web/offices/pac/mpep/s2163.html",
    note: "USPTO examination guidance concerning written-description support.",
  },
  mpep2173: {
    title: "MPEP § 2173: Claim Definiteness",
    href: "https://www.uspto.gov/web/offices/pac/mpep/s2173.html",
    note: "USPTO examination guidance concerning clarity, terminology, and claim definiteness.",
  },
  usc112: {
    title: "35 U.S.C. § 112",
    href: "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title35-section112&num=0&edition=prelim",
    note: "Official U.S. Code text addressing the specification and claims.",
  },
};

function sources(...ids) {
  return ids.map((id) => OFFICIAL_SOURCES[id]);
}

export const guideCategories = [
  {
    id: "foundations",
    label: "Foundations",
    description: "Move from an inventor disclosure to an aligned application plan.",
  },
  {
    id: "claims",
    label: "Claim drafting",
    description: "Define claim boundaries and build useful fallback positions.",
  },
  {
    id: "specification",
    label: "Specification",
    description: "Explain the claim architecture and illustrated implementations clearly.",
  },
  {
    id: "prosecution",
    label: "Prosecution",
    description: "Understand how claim trees may be restructured after examination.",
  },
  {
    id: "reference",
    label: "Quick reference",
    description: "Use concise language rules, audits, and drafting prompts while working.",
  },
];

export const guides = [
  {
    slug: "application-workflow",
    title: "From Disclosure to an Aligned Application",
    shortTitle: "Application workflow",
    category: "foundations",
    readingTime: "8 min",
    description: "A two-pass workflow for discovering the inventive story, building claim architecture, and aligning the specification.",
    takeaway: "Discover the invention first, then align the filing draft around the claims, support, terminology, and illustrated implementations.",
    useWhen: [
      "You have inventor materials but no stable claim architecture.",
      "You are deciding what belongs in the claims, Summary, figures, or Detailed Description.",
      "You are reviewing a draft for terminology and support consistency.",
    ],
    sections: [
      {
        id: "scope",
        title: "Start with the right scope",
        label: "Caution",
        paragraphs: [
          "This guide is a practice framework for U.S. utility applications. The sequence may need to change for a provisional filing, a design or plant application, a different jurisdiction, or a technology with specialized disclosure conventions.",
        ],
        callout: {
          tone: "caution",
          title: "Educational framework",
          text: "Use the workflow to organize drafting judgment. It does not replace current law, firm practice, client instructions, or review by the responsible practitioner.",
        },
      },
      {
        id: "two-passes",
        title: "Work in two passes",
        label: "Practice suggestion",
        paragraphs: [
          "Trying to draft filing-ready prose while still discovering the invention often produces inconsistent terms and a list of disconnected features. Separate discovery from filing alignment.",
        ],
        table: {
          caption: "Two-pass drafting model",
          headers: ["Pass", "Primary question", "Useful outputs"],
          rows: [
            ["Discovery", "What was built or proposed, and what technical relationship matters?", "Feature map, invention thesis, terminology sheet, operative chain"],
            ["Filing alignment", "How should the supported invention be claimed and presented?", "Independent claim spine, dependent tree, filing Summary, figure narratives, consistency audit"],
          ],
        },
      },
      {
        id: "discovery-pass",
        title: "Discovery pass",
        label: "Practice suggestion",
        steps: [
          "Inventory the disclosure, drawings, data, and known implementation variants.",
          "Identify the technical environment and the problem the work addresses.",
          "Map the main components, operations, relationships, inputs, outputs, and feedback paths.",
          "Write one sentence stating the proposed technical mechanism and resulting operation.",
          "Choose one preferred term for each important component, data object, state, and actor.",
          "Mark uncertainty instead of silently filling gaps in the inventor's disclosure.",
        ],
        worksheet: {
          title: "Discovery worksheet",
          items: [
            "Technical problem or constraint",
            "Proposed mechanism",
            "System boundary",
            "Input → processing or correction → output",
            "Feedback or verification loop",
            "Important alternatives",
            "Reported technical results and their support",
          ],
        },
      },
      {
        id: "claim-architecture-pass",
        title: "Build the claim architecture",
        label: "Practice suggestion",
        paragraphs: [
          "Reduce each proposed independent claim to a plain-language spine. Then identify narrower positions that attach to nouns and relationships already introduced by the parent.",
        ],
        steps: [
          "Choose the commercially and technically meaningful claim categories.",
          "Define the boundary of each independent claim, including what is inside the claim and what is merely part of the operating environment.",
          "Preserve the identity of important information and the cause-and-effect chain.",
          "Build sibling branches for alternatives and chains for intentionally cumulative refinements.",
          "Confirm support for each complete combination, not merely each word in isolation.",
        ],
      },
      {
        id: "section-jobs",
        title: "Give each section one primary job",
        label: "Practice suggestion",
        table: {
          caption: "Application section map",
          headers: ["Section", "Primary job"],
          rows: [
            ["Technical Field", "Identify the general technical field."],
            ["Background", "Provide restrained technical context or the condition motivating the disclosure."],
            ["Summary", "Present the claim architecture as readable technical prose."],
            ["Brief Description of Drawings", "State briefly what each view illustrates."],
            ["Detailed Description", "Explain illustrated and other supported implementations, relationships, and operations."],
            ["Claims", "Define the requested legal combinations."],
            ["Abstract", "Provide a concise overview for search and rapid review."],
          ],
        },
      },
      {
        id: "alignment-pass",
        title: "Run the alignment pass",
        label: "Rule",
        paragraphs: [
          "The filed disclosure should support the claimed subject matter and use terminology clearly enough for a reader to understand the claim boundaries. Later amendments cannot be used to add unsupported technical subject matter.",
        ],
        bullets: [
          "Trace every independent limitation to the original disclosure.",
          "Confirm that the Summary covers each important independent claim family.",
          "Confirm that figures and their descriptions explain important claimed relationships where applicable.",
          "Use one stable term for one concept unless a distinction is intentional.",
          "Separate measured results from predictions, goals, and possible advantages.",
          "Review categorical statements about what every embodiment allegedly requires.",
        ],
      },
    ],
    checklist: [
      "The invention thesis identifies a technical mechanism, not only an advantage.",
      "The system boundary and principal actors are clear.",
      "Inputs, processing, outputs, and feedback can be traced.",
      "Independent claim families have deliberate commercial or technical roles.",
      "Dependent branches provide meaningful narrower positions.",
      "Important terms remain consistent across claims and specification.",
      "Every claimed combination has identifiable original support.",
      "Illustrated embodiments are described concretely before alternatives.",
      "Benefits are tied to disclosed mechanisms and appropriately qualified.",
      "Uncertainty and missing inventor input are visible to the reviewer.",
    ],
    sources: sources("utilityGuide", "mpep608", "mpep2163", "mpep2173", "usc112"),
    related: ["independent-claims", "dependent-claims", "summary-of-invention", "figure-narratives"],
  },
  {
    slug: "independent-claims",
    title: "Drafting Independent Claims",
    shortTitle: "Independent claims",
    category: "claims",
    readingTime: "9 min",
    description: "A relationship-first method for defining a useful claim boundary without losing the technical story.",
    takeaway: "An independent claim should state a supported combination whose components, information, and causal relationships work together to produce the claimed operation.",
    useWhen: [
      "You are converting an invention map into a first claim set.",
      "A draft claim lists components but does not explain how they cooperate.",
      "You are deciding whether system, method, medium, module, or other claim perspectives add meaningful coverage.",
    ],
    sections: [
      {
        id: "legal-foundation",
        title: "State the combination clearly",
        label: "Rule",
        paragraphs: [
          "A claim should particularly point out and distinctly claim the subject matter regarded as the invention. The specification should support the claimed combination and convey possession of that subject matter.",
          "Clarity does not require maximum detail. It requires enough positive structure, operation, and relationship language to define what the claim includes.",
        ],
      },
      {
        id: "invention-thesis",
        title: "Write the invention thesis first",
        label: "Practice suggestion",
        paragraphs: [
          "Before claim syntax, describe the inventive mechanism in one sentence. Name the inputs, the meaningful processing or relationship, and the resulting operation.",
        ],
        example: {
          title: "Hypothetical equipment-monitoring system",
          before: "The invention improves equipment reliability.",
          after: "A controller evaluates current sensor data against an equipment-specific baseline and, when the comparison satisfies a maintenance condition, generates a control output for the monitored equipment.",
          body: "The revised thesis identifies information, comparison, condition, and output rather than claiming a result in the abstract.",
        },
      },
      {
        id: "claim-boundary",
        title: "Choose the boundary deliberately",
        label: "Practice suggestion",
        bullets: [
          "Identify the product, activity, module, or stored instruction set that a commercial actor may make, use, sell, or perform.",
          "Place inside the claim only the components or acts needed for the selected combination.",
          "Describe external devices as part of the operating environment when the claimed article merely communicates with them.",
          "Avoid importing preferred materials, geometry, protocols, or numerical values unless they serve the claim strategy.",
          "Use separate independent roots only when they preserve a meaningfully different boundary or perspective.",
        ],
        callout: {
          tone: "caution",
          title: "Category is not a template checkbox",
          text: "Do not add a method or computer-readable-medium claim merely because similar applications contain one. Each claim family should match the disclosed technology and intended coverage.",
        },
      },
      {
        id: "construct-system-claim",
        title: "Construct a system claim from the technical chain",
        label: "Practice suggestion",
        steps: [
          "Introduce the system and its principal structural or logical elements.",
          "State the relationships that give those elements a role in the combination.",
          "Introduce important inputs with stable identities and sources.",
          "State the determination, transformation, or control operation using those inputs.",
          "Connect the operation to its result with explicit causation or timing where material.",
          "Stop before adding details that belong in narrower dependent claims.",
        ],
        example: {
          title: "From inventory to relationship",
          before: "A system comprising a sensor, a controller, and an actuator.",
          after: "A system comprising a sensor configured to generate condition data for a monitored assembly, an actuator operatively coupled to the monitored assembly, and a controller configured to determine a control state based on the condition data and cause the actuator to operate according to the control state.",
          body: "The revised language gives each component a relationship and a role. Whether this wording is appropriate still depends on support and prior art.",
        },
      },
      {
        id: "claim-perspectives",
        title: "Translate the core across claim perspectives",
        label: "Practice suggestion",
        table: {
          caption: "Common perspective shifts",
          headers: ["Perspective", "Primary focus", "Drafting question"],
          rows: [
            ["System or apparatus", "Configured components and their relationships", "What machine or article contains the operative combination?"],
            ["Method", "Actual performance of operations", "Who performs each act, using what information, and in what necessary order?"],
            ["Computer-readable medium", "Stored instructions and processor-executable operations", "Does the software meaningfully embody the claimed operation?"],
            ["Module or controller", "A separately supplied subsystem and its interfaces", "Which external components should remain outside this claim boundary?"],
            ["Manufacturing or use method", "A supported sequence producing or using an article", "Are the claimed acts actually disclosed and attributable to a relevant actor?"],
          ],
        },
      },
      {
        id: "scope-controls",
        title: "Control breadth with relationships",
        label: "Practice suggestion",
        paragraphs: [
          "A broad noun can remain broad while its relationship to another element supplies the meaningful limitation. Before narrowing a component to a species, ask whether placement, correspondence, data identity, causation, timing, or feedback better captures the inventive distinction.",
        ],
        table: {
          caption: "Relationship questions",
          headers: ["Dimension", "Question"],
          rows: [
            ["Correspondence", "Is a particular sensor, record, or output associated with a particular physical or logical item?"],
            ["Information", "What data are generated, received, compared, or transformed, and where do they come from?"],
            ["Causation", "What determination causes the next operation?"],
            ["Timing", "Must an operation occur before or after another operation?"],
            ["Feedback", "Does the system verify that a commanded result occurred?"],
            ["Allocation", "Which actor performs each operation locally, remotely, or in a distributed arrangement?"],
          ],
        },
      },
      {
        id: "independent-audit",
        title: "Read the claim as a skeptical stranger",
        label: "Caution",
        worksheet: {
          title: "Independent-claim audit",
          items: [
            "What exact combination is mandatory?",
            "Can every introduced noun be identified unambiguously?",
            "Does each functional element have an actor and object?",
            "Are important data objects distinguishable from one another?",
            "Are causal and temporal relationships express where they matter?",
            "Does any phrase merely state a desired benefit?",
            "Has a preferred implementation been imported without a strategic reason?",
            "Does the original disclosure support the full combination?",
            "Could a commercially realistic implementation satisfy the wording?",
          ],
        },
      },
    ],
    checklist: [
      "The claim has a deliberate statutory and commercial perspective.",
      "The preamble and body describe one coherent claim boundary.",
      "Each important component has a relationship or operative role.",
      "Inputs and outputs retain stable identities.",
      "The claim states causation or timing when it is part of the inventive chain.",
      "Benefits are translated into positive structure or operations.",
      "Optional examples are reserved for the specification.",
      "Terms have clear antecedent basis and consistent meaning.",
      "The full combination has original written-description support.",
      "Narrower features have been considered for dependent branches.",
    ],
    sources: sources("usc112", "mpep2163", "mpep2173", "mpep608"),
    related: ["application-workflow", "dependent-claims", "summary-of-invention", "drafting-language"],
  },
  {
    slug: "dependent-claims",
    title: "Building Useful Dependent Claims",
    shortTitle: "Dependent claims",
    category: "claims",
    readingTime: "11 min",
    description: "A practical system for mining support, ranking narrower positions, and building deliberate claim trees.",
    takeaway: "A good dependent claim is a narrower combination you would still value if the broader claim were rejected, amended, or challenged.",
    useWhen: [
      "You have an independent claim and need supported fallback positions.",
      "A claim set has many details but no clear strategic hierarchy.",
      "You need to choose between sibling claims and cumulative chains.",
    ],
    sections: [
      {
        id: "dependency-mechanics",
        title: "Understand what the child inherits",
        label: "Rule",
        paragraphs: [
          "Under 35 U.S.C. § 112(d), a dependent claim refers to an earlier claim, incorporates its limitations, and adds a further limitation. A child cannot replace or contradict a limitation inherited from its parent.",
        ],
        example: {
          title: "Expand the dependency",
          before: "Claim 1 requires A + B + C. Claim 2 depends from claim 1 and adds D.",
          after: "Claim 2 requires A + B + C + D.",
          body: "Every later review should consider the expanded combination, including all intervening claims.",
        },
      },
      {
        id: "find-the-spine",
        title: "Start from the independent-claim spine",
        label: "Practice suggestion",
        steps: [
          "Rewrite the parent claim as a plain-language list of mandatory elements and relationships.",
          "Mark what the parent already requires so a child does not merely paraphrase it.",
          "Return to the corresponding figures and specification passages.",
          "Look for supported structures, configurations, states, data, processing, and relationships that attach to introduced nouns.",
          "Record the complete support for the proposed combination.",
        ],
        callout: {
          tone: "practice",
          title: "Search the disclosure as a whole",
          text: "Useful dependent features may appear in figures, implementation details, operating sequences, alternatives, or inventor explanations. Do not search only one named section.",
        },
      },
      {
        id: "feature-dimensions",
        title: "Mine by feature dimension",
        label: "Practice suggestion",
        table: {
          caption: "Dependent-claim mining prompts",
          headers: ["Dimension", "Questions"],
          rows: [
            ["Components and species", "What additional component appears, and what specific forms can a broader element take?"],
            ["Quantity and placement", "Do respective, plurality, adjacency, nesting, or alignment relationships matter?"],
            ["Coupling", "How are elements physically, mechanically, electrically, or communicatively related?"],
            ["Information and processing", "What particular data are received, generated, compared, filtered, classified, or stored?"],
            ["Causation and sequence", "What event causes the next operation, and is ordering technically meaningful?"],
            ["State and feedback", "What state transition occurs, and is the result verified?"],
            ["Exceptions", "What happens after failure, mismatch, timeout, or uncertainty?"],
            ["Architecture", "Which operations are local, remote, centralized, or distributed?"],
          ],
        },
      },
      {
        id: "strategic-jobs",
        title: "Give each candidate a job",
        label: "Practice suggestion",
        table: {
          caption: "Strategic jobs for narrower claims",
          headers: ["Job", "Question to ask"],
          rows: [
            ["Prior-art fallback", "What supported difference might remain if the broad claim is unavailable?"],
            ["Commercial embodiment", "Does the limitation cover a configuration the applicant expects to practice?"],
            ["Design-around blocker", "Does it cover a predictable alternative a competitor may retain?"],
            ["Proof-friendly position", "Could the limitation be observed, tested, documented, or reasonably inferred?"],
            ["Technical grounding", "Does it add concrete processing, structure, or interaction?"],
            ["Species protection", "Is a narrower component, range, material, protocol, or algorithm worth protecting?"],
            ["Failure-mode protection", "Does it cover verification, alerting, retry, restriction, or recovery?"],
          ],
        },
      },
      {
        id: "rank-candidates",
        title: "Rank before you draft",
        label: "Practice suggestion",
        worksheet: {
          title: "Candidate scorecard",
          items: [
            "Patentability value: Does the combination create a meaningful distinction?",
            "Commercial value: Is it likely to be practiced?",
            "Durability: Can it be removed without degrading the product or process?",
            "Detectability: How could practice of the limitation be shown?",
            "Scope: Does it narrow meaningfully without collapsing to trivia?",
            "Support: Is the complete combination disclosed?",
            "Clarity: Can it be expressed through objective structure or acts?",
            "Dependency fit: Does it logically narrow this parent?",
          ],
        },
      },
      {
        id: "siblings-and-chains",
        title: "Use siblings for alternatives and chains for cumulative logic",
        label: "Practice suggestion",
        table: {
          caption: "Choose the dependency shape deliberately",
          headers: ["Shape", "Use it when", "Effect"],
          rows: [
            ["Sibling claims", "Two refinements are alternatives or should remain independently available.", "Each child inherits the same parent without inheriting the other sibling."],
            ["Claim chain", "A later operation or structure logically requires an earlier refinement.", "Each child accumulates every intervening limitation."],
            ["Separate independent root", "A branch has a materially different valuable boundary.", "The branch does not automatically inherit limitations added to another root."],
          ],
        },
        example: {
          title: "Feedback branch",
          before: "Claim 2 adds verification. Claim 3 adds an alert but depends directly from claim 1.",
          after: "Claim 2 adds verification. Claim 3 depends from claim 2 and generates an alert when verification identifies a mismatch.",
          body: "The alert intentionally depends on the verification that supplies its trigger.",
        },
      },
      {
        id: "broad-to-specific",
        title: "Build a broad-to-specific ladder",
        label: "Example",
        paragraphs: [
          "Avoid jumping from a broad component directly to an arbitrary production detail. Create useful intermediate positions where the disclosure supports them.",
        ],
        steps: [
          "Important relationship: a respective sensor is associated with each monitored region.",
          "Important information: each sensor generates region-specific condition data.",
          "Component species: each sensor includes an optical sensor.",
          "Operating detail: condition data are generated from interruption of an optical path.",
        ],
      },
      {
        id: "drafting-hooks",
        title: "Use the grammatical hook that matches the limitation",
        label: "Practice suggestion",
        table: {
          caption: "Common dependent-claim constructions",
          headers: ["Purpose", "Typical construction"],
          rows: [
            ["Add an element", "The system of claim 1, further comprising ..."],
            ["Narrow an element", "The system of claim 1, wherein the sensor comprises ..."],
            ["Define a relationship", "The system of claim 1, wherein the sensor is positioned adjacent to ..."],
            ["Add subcomponents", "The system of claim 1, wherein the mechanism comprises ..."],
            ["Narrow an operation", "The method of claim 10, wherein determining ... comprises ..."],
            ["Add causation", "The method of claim 10, further comprising, responsive to determining ..., causing ..."],
            ["Add verification", "The method of claim 10, further comprising receiving updated data after ... and determining ..."],
          ],
        },
        callout: {
          tone: "caution",
          title: "State what the claim requires",
          text: "Optional and exemplary expressions such as may, optionally, preferably, for example, and such as generally belong in the specification rather than in a limitation intended to narrow the claim.",
        },
      },
      {
        id: "promotion-test",
        title: "Apply the promotion test",
        label: "Practice suggestion",
        paragraphs: [
          "For an important candidate, ask whether you would be comfortable adding the limitation to an independent claim if the broader position were unavailable. A yes answer is a strong signal that the child is a meaningful fallback, although not every useful species claim must pass this test.",
        ],
        worksheet: {
          title: "Final candidate review",
          items: [
            "Which parent should this depend from?",
            "What becomes mandatory after fully expanding the chain?",
            "What technical and strategic job does the limitation perform?",
            "Where is the complete combination supported?",
            "How might the limitation distinguish plausible art?",
            "How might practice be detected?",
            "How easily could the feature be replaced?",
            "Would this limitation be worth promoting?",
          ],
        },
      },
    ],
    checklist: [
      "The parent claim has been expanded and understood.",
      "The child adds a genuine further limitation.",
      "The limitation does not replace or contradict the parent.",
      "The feature attaches clearly to an introduced noun or relationship.",
      "The claim has at least one identifiable strategic job.",
      "Alternatives are siblings unless their combination is intentional.",
      "Chains include only technically and strategically related limitations.",
      "Useful intermediate breadth positions have been considered.",
      "The wording states what is required without optional examples.",
      "Antecedent basis and element identity are clear.",
      "The complete inherited combination is supported.",
      "Commercial practice and detectability have been considered.",
      "A plausible design-around has been simulated.",
      "The strongest fallbacks pass the promotion test.",
    ],
    sources: sources("usc112", "mpep2163", "mpep2173", "mpep707"),
    related: ["independent-claims", "prosecution-fallbacks", "application-workflow", "quick-reference"],
  },
  {
    slug: "summary-of-invention",
    title: "Drafting the Summary of the Invention",
    shortTitle: "Summary",
    category: "specification",
    readingTime: "10 min",
    description: "A claim-anchored framework for turning the claim strategy into clear, readable specification prose.",
    takeaway: "The Summary should present the claim architecture as an intelligible technical story, not repeat the abstract or inventory every disclosed feature.",
    useWhen: [
      "The independent-claim structure is substantially established.",
      "A Summary reads like a generic marketing paragraph or copied claim fragments.",
      "Claims changed during drafting or prosecution and the Summary needs alignment review.",
    ],
    sections: [
      {
        id: "role",
        title: "Understand the Summary's job",
        label: "USPTO procedure",
        paragraphs: [
          "USPTO guidance describes the Summary as a brief statement of the invention's nature and substance. It should communicate the specific invention and remain consistent with the claimed subject matter.",
        ],
        table: {
          caption: "Keep the sections distinct",
          headers: ["Section", "Primary question"],
          rows: [
            ["Abstract", "What is the disclosure generally about, stated concisely?"],
            ["Summary", "What inventive subject matter and claim perspectives does the application present?"],
            ["Detailed Description", "How can supported implementations be structured and operated?"],
            ["Claims", "What precise combinations are requested?"],
          ],
        },
      },
      {
        id: "draft-twice",
        title: "Draft it twice",
        label: "Practice suggestion",
        table: {
          caption: "Two summaries with different purposes",
          headers: ["Draft", "When", "Purpose"],
          rows: [
            ["Discovery summary", "Before claims are stable", "Identify the technical problem, mechanism, operation, and meaningful alternatives."],
            ["Filing Summary", "After independent claim architecture is substantially established", "Present each important claim family and selected refinements in aligned prose."],
          ],
        },
      },
      {
        id: "summary-matrix",
        title: "Build a Summary matrix",
        label: "Practice suggestion",
        paragraphs: [
          "Map the common operative core once, then identify the boundary and perspective of each independent claim family. This exposes omissions and prevents a method or module claim from being described as though it necessarily includes the entire physical system.",
        ],
        worksheet: {
          title: "Summary matrix columns",
          items: [
            "Claim family and category",
            "Claimed boundary",
            "Central components or acts",
            "Common inventive core",
            "Unique perspective",
            "Selected dependent themes",
            "Planned Summary paragraph",
          ],
        },
      },
      {
        id: "core-and-wrappers",
        title: "Separate the operative core from the claim wrappers",
        label: "Practice suggestion",
        table: {
          caption: "One technical story, multiple claim perspectives",
          headers: ["Layer", "Example focus"],
          rows: [
            ["Common operative core", "condition data → comparison → control determination → output → optional verification"],
            ["System wrapper", "Components, processors, memory, and their configured relationships"],
            ["Method wrapper", "Performance of the operations by identified actors"],
            ["Medium wrapper", "Stored instructions causing processor-executable operations"],
            ["Module wrapper", "A separately supplied controller and its interfaces to external components"],
          ],
        },
      },
      {
        id: "claim-anchored-narrative",
        title: "Use claim-anchored narrative",
        label: "Practice suggestion",
        paragraphs: [
          "Retain important claim nouns, data identities, structural relationships, causation, timing, and boundaries. Replace claim fragments and punctuation with connected specification prose.",
        ],
        example: {
          title: "Preserve the technical chain",
          before: "The system receives information, processes it, and provides an output.",
          after: "In some implementations, a controller receives condition data generated by a sensor associated with monitored equipment and baseline data associated with the equipment. The controller determines a control state based on a comparison of the condition data with the baseline data and generates a control output corresponding to the control state.",
          body: "The revised version identifies the source and role of each data object and the relationship producing the output.",
        },
      },
      {
        id: "macro-structure",
        title: "Use a readable macro-structure",
        label: "Practice suggestion",
        steps: [
          "Optionally orient the reader to the technical area and central mechanism.",
          "Present the primary system or apparatus aspect.",
          "Present a method aspect when it is part of the claim strategy.",
          "Present a medium or other independent aspect only when meaningful and supported.",
          "Group selected dependent refinements by technical theme rather than claim number.",
          "Optionally conclude with a restrained mechanism-linked result or meaningful architecture alternative.",
        ],
        callout: {
          tone: "practice",
          title: "A default, not a mandate",
          text: "The best order depends on the invention and claim set. A physical assembly may need apparatus, subassembly, and method-of-operation aspects with no medium paragraph.",
        },
      },
      {
        id: "refinement-themes",
        title: "Group refinements by technical theme",
        label: "Practice suggestion",
        bullets: [
          "Structures, placement, and correspondence",
          "Sensing, data identity, and measurement",
          "Authentication, authorization, or validation",
          "Processing, classification, comparison, or correction",
          "Control, feedback, and failure response",
          "Local, remote, or distributed architecture",
        ],
        paragraphs: [
          "Emphasize the independent core and broad refinements. Exact geometry, implementation code, packet formats, lengthy species lists, and routine production details usually belong in the Detailed Description.",
        ],
      },
      {
        id: "language-and-benefits",
        title: "Frame aspects carefully and explain benefits through mechanisms",
        label: "Caution",
        example: {
          title: "Mechanism before advantage",
          before: "The invention always improves reliability.",
          after: "In some implementations, obtaining updated sensor data after issuance of a control command enables the controller to identify a mismatch between a commanded state and a detected state.",
          body: "The revised sentence confines the statement to an implementation and explains the operation producing the possible result.",
        },
        callout: {
          tone: "caution",
          title: "Review universal language",
          text: "Use statements about the invention as a whole only when that characterization is deliberate. A general exemplary disclaimer may not cure an earlier categorical description.",
        },
      },
      {
        id: "summary-audits",
        title: "Run four fast audits",
        label: "Practice suggestion",
        table: {
          caption: "Summary quality checks",
          headers: ["Audit", "Question"],
          rows: [
            ["Hide the claims", "Can the reader identify the product or activity, operative chain, and principal claim perspectives from the Summary alone?"],
            ["Reverse mapping", "Can each important independent claim family be located in a Summary paragraph?"],
            ["Universal language", "Does every use of must, requires, essential, all embodiments, or the invention reflect deliberate scope?"],
            ["Compression", "Does each paragraph preserve an independent family, a novelty-bearing relationship, or a useful refinement theme?"],
          ],
        },
      },
    ],
    checklist: [
      "The Summary identifies the specific technical invention.",
      "Every important independent claim family has a corresponding aspect.",
      "Claim boundaries and terminology remain aligned.",
      "Important data identities, relationships, causation, and timing are preserved.",
      "Dependent refinements are grouped by technical theme.",
      "Preferred implementation details are not presented as universal requirements.",
      "Benefits are linked to disclosed mechanisms and appropriately qualified.",
      "The Summary is not a figure walkthrough or second Detailed Description.",
      "No unsupported technical subject matter has been introduced.",
      "The Summary remains readable without reconstructing the claims.",
      "The Summary will be reviewed after material claim amendments.",
    ],
    sources: sources("mpep608", "mpep2163", "mpep2173", "usc112"),
    related: ["application-workflow", "independent-claims", "figure-narratives", "drafting-language"],
  },
  {
    slug: "figure-narratives",
    title: "Writing Figure Narratives",
    shortTitle: "Figure narratives",
    category: "specification",
    readingTime: "9 min",
    description: "A repeatable way to turn a drawing into a coherent description of structure, relationships, operation, result, and alternatives.",
    takeaway: "Do not merely inventory the boxes. Help the reader trace why the illustrated arrangement produces its result.",
    useWhen: [
      "You are drafting a Detailed Description from system, process, or assembly figures.",
      "A figure description names components but omits relationships or causal flow.",
      "You need to separate one concrete implementation from optional variants.",
    ],
    sections: [
      {
        id: "caption-versus-narrative",
        title: "Separate the caption from the narrative",
        label: "USPTO procedure",
        paragraphs: [
          "The Brief Description of the Drawings identifies what each view illustrates. The Detailed Description then refers to the figure and explains the depicted components, reference characters, relationships, and operation in sufficient detail for the disclosure.",
        ],
        example: {
          title: "Different jobs",
          before: "Brief description: FIG. 3 shows every component, connection, message, state transition, and alternative implementation of the system.",
          after: "Brief description: FIG. 3 illustrates an example monitoring system and an example operational flow of the monitoring system.",
          body: "The complete technical story belongs in the corresponding Detailed Description paragraphs.",
        },
      },
      {
        id: "figure-thesis",
        title: "Decide what job the figure performs",
        label: "Practice suggestion",
        paragraphs: [
          "Complete the sentence: This figure exists to show _____. A figure may show architecture, communication, operation, an alternative arrangement, or more than one connected story.",
        ],
        worksheet: {
          title: "Figure planning sheet",
          items: [
            "Figure thesis",
            "Traversal route",
            "Major subsystems",
            "Meaning of each line, arrow, group, or state marker",
            "Operational chain",
            "Variation axes",
            "Current and possible claim support",
          ],
        },
      },
      {
        id: "feature-map",
        title: "Map the features before writing prose",
        label: "Practice suggestion",
        table: {
          caption: "Five questions for every important depicted item",
          headers: ["Question", "Drafting purpose"],
          rows: [
            ["What is it?", "Choose a neutral, stable name."],
            ["Where is it or what contains it?", "State the spatial or hierarchical relationship."],
            ["What is it connected or related to?", "Identify physical, mechanical, electrical, communication, or logical links."],
            ["What does it receive, detect, generate, or control?", "State its function and information role."],
            ["What happens because of it?", "Connect the component to the next operation or result."],
          ],
        },
      },
      {
        id: "traversal",
        title: "Choose one traversal path",
        label: "Practice suggestion",
        bullets: [
          "Whole to parts for a system architecture",
          "Outside to inside for a housing or assembly",
          "Input to processing to output for electronics",
          "Top to bottom or left to right for a flowchart",
          "Stationary component to removable component to interface for an exploded view",
          "User to interface to controller to hardware to confirmation for an interactive system",
        ],
        paragraphs: [
          "Open with orientation, then identify the major component neighborhood before discussing specialized details. Keep the chosen route unless the technical logic requires a return to an earlier component.",
        ],
      },
      {
        id: "relationships",
        title: "Explain the links explicitly",
        label: "Practice suggestion",
        table: {
          caption: "Relationship vocabulary by function",
          headers: ["Relationship", "Examples"],
          rows: [
            ["Spatial", "within, adjacent to, supported by, aligned with, between"],
            ["Mechanical", "removably coupled, pivotably coupled, engageable with, movable between states"],
            ["Electrical or communication", "electrically coupled, communicatively coupled, configured to transmit"],
            ["Functional", "configured to detect, operable to generate, configured to control"],
            ["Causal", "based on, responsive to, upon determining, according to"],
          ],
        },
        callout: {
          tone: "caution",
          title: "Do not guess what an ambiguous line means",
          text: "A line may represent a physical connection, communication path, data flow, control flow, power, motion, user action, or merely a callout. Resolve ambiguity before describing it as a technical relationship.",
        },
      },
      {
        id: "operational-story",
        title: "Tell the operational story actor by actor",
        label: "Example",
        example: {
          title: "Give each action an actor and consequence",
          before: "Data are received, a decision is made, and a valve is opened.",
          after: "Sensor 110 generates pressure data for conduit 104 and provides the pressure data to controller 120. Controller 120 determines, based on the pressure data, that a release condition is satisfied and, responsive to the determination, transmits a control command to actuator 112. Actuator 112 moves valve 114 to an open state.",
          body: "The revised narrative identifies the source and identity of the data, the decision maker, the decision basis, the command recipient, and the physical result.",
        },
      },
      {
        id: "concrete-then-variants",
        title: "Describe one implementation before its variants",
        label: "Practice suggestion",
        paragraphs: [
          "Frame the illustrated example once, then state its depicted relationships directly. After the reader has a stable model, add a separate paragraph for supported alternatives in component type, location, integration, communication, sequence, or actor.",
        ],
        example: {
          title: "Definite inside an embodiment frame",
          before: "Sensor 110 may be coupled to conduit 104 and may generate data that may be sent to controller 120.",
          after: "In the illustrated example, sensor 110 is coupled to conduit 104 and generates pressure data for conduit 104. Sensor 110 provides the pressure data to controller 120. In other implementations, the sensor may be positioned at another location from which the pressure condition can be detected.",
          body: "The concrete paragraph conveys the illustrated relationship; the separate variation sentence supplies supported optionality.",
        },
      },
      {
        id: "figure-audits",
        title: "Run the reconstruction and numeral audits",
        label: "Rule",
        bullets: [
          "Hide the drawing and ask whether the text explains the primary components, arrangement, links, and operation.",
          "Hide the text and ask whether each major reference character and arrow can be located and understood.",
          "Confirm that each character refers consistently to the same item across views.",
          "Confirm that the description does not use a character absent from the drawing.",
          "Compare the figures and text with current claims and useful supported future positions.",
          "Spend detail in proportion to inventive importance rather than describing every conventional feature equally.",
        ],
      },
    ],
    checklist: [
      "The figure has a clear narrative thesis.",
      "The caption remains brief and the Detailed Description carries the full story.",
      "The description moves through a deliberate traversal path.",
      "The whole is introduced before specialized parts.",
      "Important spatial, mechanical, communication, and causal relationships are explicit.",
      "Every operation has an identifiable actor, input, and result.",
      "Data and states retain stable identities.",
      "Necessary ordering is preserved without imposing unnecessary sequence.",
      "One coherent implementation is described before alternatives.",
      "Reference characters are accurate and consistent.",
      "Current claim features and useful supported refinements are addressed where appropriate.",
      "Ambiguous inventor material is flagged rather than guessed.",
    ],
    sources: sources("mpep608", "mpep2163", "mpep2173", "utilityGuide"),
    related: ["drafting-language", "summary-of-invention", "application-workflow", "dependent-claims"],
  },
  {
    slug: "prosecution-fallbacks",
    title: "Restructuring Claim Trees After Examination",
    shortTitle: "Prosecution fallbacks",
    category: "prosecution",
    readingTime: "8 min",
    description: "A simplified framework for understanding allowable dependent positions, promotion choices, and downstream claim effects.",
    takeaway: "Examination may show how far down a claim tree the apparently allowable subject matter begins; the response should preserve valuable branches rather than promote every surviving child automatically.",
    useWhen: [
      "An Office action rejects a parent but identifies possible allowable subject matter in a dependent claim.",
      "You are comparing amendment of an existing independent claim with rewriting a child independently.",
      "You need to understand how adding a limitation to a root affects every descendant.",
    ],
    sections: [
      {
        id: "simplified-model",
        title: "Use the model carefully",
        label: "Caution",
        paragraphs: [
          "This guide explains claim-tree consequences, not a complete Office-action response. The actual record may involve claim construction, multiple statutory grounds, finality, restriction, interviews, evidence, continuation practice, appeal, and other procedural choices.",
        ],
        callout: {
          tone: "caution",
          title: "Read the Office action itself",
          text: "Do not treat a status label as a substitute for the examiner's stated reasoning, cited evidence, and exact treatment of each claim.",
        },
      },
      {
        id: "examiner-treatment",
        title: "Distinguish rejection from dependency treatment",
        label: "USPTO procedure",
        paragraphs: [
          "An examiner may reject a base claim while indicating that a dependent claim would be allowable if rewritten in independent form to include the limitations of its parent and any intervening claims. That signal identifies a possible narrower path; it does not decide the applicant's complete strategy.",
        ],
      },
      {
        id: "simple-tree",
        title: "Expand the tree before choosing",
        label: "Example",
        table: {
          caption: "Hypothetical claim tree",
          headers: ["Claim", "Written form", "Expanded combination"],
          rows: [
            ["1", "Independent A + B + C", "A + B + C"],
            ["2", "Claim 1 + D", "A + B + C + D"],
            ["3", "Claim 1 + E", "A + B + C + E"],
            ["4", "Claim 3 + F", "A + B + C + E + F"],
          ],
        },
        paragraphs: [
          "If the examiner identifies claim 3 as a possible allowable position, the apparent fallback is the entire A + B + C + E combination, not E in isolation.",
        ],
      },
      {
        id: "response-paths",
        title: "Compare the principal restructuring paths",
        label: "Practice suggestion",
        table: {
          caption: "Promotion choices and consequences",
          headers: ["Path", "What happens", "Main consequence"],
          rows: [
            ["Amend claim 1 to add E", "Claim 1 becomes A + B + C + E.", "Every claim depending from claim 1 now inherits E."],
            ["Rewrite claim 3 independently", "Claim 3 expressly recites A + B + C + E.", "The E branch can stand separately while another root may be argued or amended differently."],
            ["Preserve multiple roots", "Different supported combinations begin separate claim trees.", "Distinct commercial or technical branches need not inherit one another's limitations."],
          ],
        },
      },
      {
        id: "downstream-effects",
        title: "Account for every descendant",
        label: "Rule",
        paragraphs: [
          "When a parent is amended, every direct and indirect dependent claim incorporates the amended parent. A previously separate combination can disappear unless it is deliberately preserved elsewhere.",
        ],
        example: {
          title: "The hidden narrowing effect",
          before: "Claim 2 originally covered A + B + C + D.",
          after: "After E is added to claim 1, claim 2 covers A + B + C + E + D.",
          body: "The original A + B + C + D position is no longer present unless another claim preserves it.",
        },
      },
      {
        id: "redundant-and-surviving-claims",
        title: "Cancel redundancy and preserve useful children",
        label: "Practice suggestion",
        bullets: [
          "A child that adds only the limitation now promoted into its parent is ordinarily redundant and should be reconsidered.",
          "A grandchild that adds a further useful limitation may be reparented beneath the amended root.",
          "Sibling branches should be reviewed for unintended narrowing caused by the amendment.",
          "A separate root may preserve a different valuable combination that should not require the promoted limitation.",
          "Not every apparently allowable child should become independent; narrower children can remain useful beneath the newly established root.",
        ],
      },
      {
        id: "response-workflow",
        title: "Use a disciplined response workflow",
        label: "Practice suggestion",
        steps: [
          "Map every claim to each stated ground and cited reference.",
          "Expand each dependency chain in full.",
          "Identify the broadest supported position the examiner appears to treat favorably.",
          "Decide which broader rejections remain worth contesting.",
          "Compare amendment, independent rewriting, cancellation, and branch-preservation effects.",
          "Check support, clarity, and consistency for every proposed amendment.",
          "Update the claim tree and review the Summary and Detailed Description for continued alignment.",
        ],
      },
    ],
    checklist: [
      "Each claim's exact examiner treatment has been read in context.",
      "Every dependent claim has been expanded through all intervening parents.",
      "The apparently allowable combination is identified as a whole.",
      "Amendment and independent-rewrite paths have been compared.",
      "The effect on every descendant has been mapped.",
      "Redundant children have been identified.",
      "Useful grandchildren and sibling branches have been preserved deliberately.",
      "No new or amended limitation exceeds original support.",
      "Terminology and antecedent basis remain clear after restructuring.",
      "The specification and Summary have been reviewed for alignment.",
      "The response reflects the responsible practitioner's strategy for the actual record.",
    ],
    sources: sources("mpep707", "usc112", "mpep2163", "mpep2173"),
    related: ["dependent-claims", "independent-claims", "summary-of-invention", "quick-reference"],
  },
  {
    slug: "drafting-language",
    title: "Drafting Language: Definite, Optional, and Capable",
    shortTitle: "Drafting language",
    category: "reference",
    readingTime: "7 min",
    description: "A section-aware guide to direct embodiment language, genuine alternatives, capability, claim clarity, and mechanism-based results.",
    takeaway: "Frame an implementation once, describe it clearly, and use optional language only when it adds a real alternative or capability.",
    useWhen: [
      "A specification contains repeated may, can, that, it, or configured-to constructions.",
      "You are deciding whether direct embodiment language is too limiting.",
      "A claim or Summary states a benefit without the mechanism producing it.",
    ],
    sections: [
      {
        id: "section-aware",
        title: "Choose language by document context",
        label: "Practice suggestion",
        table: {
          caption: "A practical context map",
          headers: ["Context", "Useful default", "Use may for", "Use can for"],
          rows: [
            ["Figure-specific description", "Direct statements inside an example or embodiment frame", "Supported alternatives or variants", "Capability or a possible result"],
            ["Summary", "Direct description within an aspect or implementation", "Optional refinements and alternatives", "A mechanism-linked possible result"],
            ["Claims", "Positive language stating what is required", "Ordinarily avoid optional wording", "Ordinarily avoid wording that leaves the limitation optional"],
            ["Variations paragraph", "Clearly identify the base implementation", "Alternative structures, locations, actors, or operations", "Supported capability"],
          ],
        },
      },
      {
        id: "definite-embodiment",
        title: "Be definite inside a limited frame",
        label: "Practice suggestion",
        paragraphs: [
          "A direct sentence about an identified embodiment is not the same as a universal statement about every implementation. The frame can do the qualifying work that repeated modal verbs often attempt to do.",
        ],
        example: {
          title: "One frame, clear relationships",
          before: "System 100 may include sensor 110. Sensor 110 may generate data and may provide the data to controller 120.",
          after: "In the illustrated embodiment, system 100 includes sensor 110 and controller 120. Sensor 110 generates condition data and provides the condition data to controller 120.",
          body: "A later variations paragraph can disclose supported alternatives without making the depicted relationship sound speculative.",
        },
      },
      {
        id: "may-can-direct",
        title: "Give each verb one job",
        label: "Practice suggestion",
        table: {
          caption: "Verb selection",
          headers: ["Wording", "Best use", "Example"],
          rows: [
            ["is, includes, receives, generates", "What the framed implementation has or does", "Sensor 110 generates condition data."],
            ["may", "A genuine alternative, refinement, or variant", "Sensor 110 may be positioned within or adjacent to housing 104."],
            ["can", "A capability or possible result", "Controller 120 can identify a mismatch from updated condition data."],
            ["is configured to", "A designed functional capability when that meaning is intended", "Controller 120 is configured to determine a control state."],
          ],
        },
        callout: {
          tone: "caution",
          title: "Do not perform blind substitutions",
          text: "Uses, performs, is configured to, and can are not interchangeable. Ask whether the text means actual operation, designed capability, or merely one possible use.",
        },
      },
      {
        id: "universal-language",
        title: "Review universal invention language deliberately",
        label: "Caution",
        bullets: [
          "the present invention is",
          "the invention requires",
          "all embodiments include",
          "a necessary or essential feature is",
          "the system must always",
          "the only implementation",
        ],
        paragraphs: [
          "These expressions may be appropriate when universality is intentional, but they deserve specific review. For narrower implementations, use frames such as in some implementations, according to one aspect, or in the illustrated example.",
        ],
      },
      {
        id: "claim-language",
        title: "State positive limitations in claims",
        label: "Rule",
        paragraphs: [
          "A dependent claim should make the added limitation mandatory and clear. Optional examples can create uncertainty about whether the claim is actually narrowed.",
        ],
        example: {
          title: "Claim the species directly",
          before: "The system of claim 1, wherein the sensor may comprise a sensor such as an optical sensor.",
          after: "The system of claim 1, wherein the sensor comprises an optical sensor.",
          body: "Disclose other supported sensor species in the specification or in separate appropriately structured claims.",
        },
      },
      {
        id: "mechanism-results",
        title: "Replace unsupported superlatives with mechanisms",
        label: "Practice suggestion",
        example: {
          title: "Explain what produces the result",
          before: "The model outperforms alternative systems and significantly improves accuracy.",
          after: "In the reported evaluation, the model produced a lower measured error under the stated test conditions. In some implementations, correction based on the additional input can reduce disagreement between the generated output and a reference value.",
          body: "The revision separates a reported result from a possible implementation benefit. Preserve the actual metric, comparison, and conditions when the source supports them.",
        },
        callout: {
          tone: "caution",
          title: "Significance has a technical meaning",
          text: "Use statistically significant only when a supported statistical analysis establishes it. Otherwise identify the measured difference or use restrained descriptive language.",
        },
      },
      {
        id: "pronouns-and-antecedents",
        title: "Use pronouns only when identity remains unmistakable",
        label: "Practice suggestion",
        paragraphs: [
          "Words such as it, that, this, and the are not prohibited. The problem is ambiguity. Repeat the component or data name when multiple possible antecedents exist or when the relationship carries claim significance.",
        ],
        example: {
          title: "Preserve the actor",
          before: "The sensor provides the data to the controller, and it determines the state.",
          after: "The sensor provides the condition data to the controller, and the controller determines the state based on the condition data.",
          body: "The revision removes uncertainty about which component performs the determination and which information supplies its basis.",
        },
      },
    ],
    checklist: [
      "Each paragraph is framed at the intended implementation or aspect level.",
      "Direct verbs describe the concrete implementation clearly.",
      "May introduces a genuine supported alternative rather than general hedging.",
      "Can describes capability or a possible result when that meaning is intended.",
      "Configured to is used for designed functional capability, not as a reflexive replacement.",
      "Claims state mandatory limitations without optional examples.",
      "Universal invention language has been reviewed deliberately.",
      "Pronouns have unmistakable antecedents.",
      "Data, components, and states retain stable names.",
      "Comparative or statistical statements preserve the supported metric and conditions.",
      "Advantages are connected to disclosed technical mechanisms.",
    ],
    sources: sources("mpep608", "mpep2163", "mpep2173", "usc112"),
    related: ["figure-narratives", "summary-of-invention", "independent-claims", "quick-reference"],
  },
  {
    slug: "quick-reference",
    title: "Patent Drafting Quick Reference",
    shortTitle: "Quick reference",
    category: "reference",
    readingTime: "5 min",
    description: "A compact routing guide, relationship checklist, and final audit for U.S. utility drafting practice.",
    takeaway: "When stuck, trace the claimed technical story: introduced noun → relationship → information or state → operation → result → supported fallback.",
    useWhen: [
      "You need a fast drafting prompt without reading a full guide.",
      "You are reviewing a claim or specification paragraph before handoff.",
      "ScopeCraft feedback identifies a problem and you need the next practical check.",
    ],
    sections: [
      {
        id: "route-by-task",
        title: "Start with the task in front of you",
        label: "Quick reference",
        table: {
          caption: "Guide router",
          headers: ["Task", "Go to", "First question"],
          rows: [
            ["Organize an inventor disclosure", "Application workflow", "What is the technical mechanism and operative chain?"],
            ["Draft a broad claim", "Independent claims", "What supported combination defines the intended boundary?"],
            ["Add fallback positions", "Dependent claims", "What narrower position would still be worth owning?"],
            ["Draft the Summary", "Summary", "What claim architecture must the prose present?"],
            ["Describe a drawing", "Figure narratives", "What job does this figure perform?"],
            ["Handle an allowable child", "Prosecution fallbacks", "What happens to every branch if a limitation moves to the root?"],
            ["Choose may, can, or direct wording", "Drafting language", "Do I mean actual operation, an alternative, or capability?"],
          ],
        },
      },
      {
        id: "technical-story",
        title: "Trace the technical story",
        label: "Practice suggestion",
        steps: [
          "Name the relevant system, article, activity, or module.",
          "Introduce the important components, actors, data, or states.",
          "State how those items are related.",
          "Identify what information enters and where it comes from.",
          "State the determination, transformation, or control operation.",
          "Connect the operation to the next event with causation or necessary timing.",
          "State the physical or informational result.",
          "Add feedback, exception handling, or a narrower supported refinement where valuable.",
        ],
      },
      {
        id: "claim-minute",
        title: "One-minute claim audit",
        label: "Quick reference",
        bullets: [
          "Boundary: Is it clear what the claim covers and what is external?",
          "Actors: Does every operation have an identifiable performer?",
          "Antecedents: Can every the, respective, corresponding, first, and second be traced?",
          "Relationships: Are placement, coupling, information flow, and causation explicit where material?",
          "Mandatory scope: Does the claim avoid optional examples?",
          "Support: Is the complete combination disclosed?",
          "Fallbacks: Are useful narrower positions preserved without accidental long chains?",
        ],
      },
      {
        id: "spec-minute",
        title: "One-minute specification audit",
        label: "Quick reference",
        bullets: [
          "Frame the embodiment or aspect once.",
          "Describe the concrete implementation directly.",
          "Preserve stable component, data, and state names.",
          "Explain who does what, based on what, and what happens next.",
          "Move supported alternatives to a distinct variations sentence or paragraph.",
          "Tie claimed benefits to mechanisms and reported results to actual conditions.",
          "Review universal language and unsupported certainty.",
        ],
      },
      {
        id: "common-repairs",
        title: "Common repairs",
        label: "Example",
        table: {
          caption: "From weak drafting to a better next question",
          headers: ["Weak pattern", "Better direction", "Ask"],
          rows: [
            ["The system improves reliability.", "State the operation that detects or prevents the failure.", "What mechanism produces the result?"],
            ["The system receives data.", "Name the data, source, and role.", "Which data, from where, and used for what?"],
            ["A decision is made.", "Identify the actor, basis, and consequence.", "Who decides, based on what, and what follows?"],
            ["The component may include ... may send ... may control ...", "Frame one implementation and write it directly.", "Which statements describe the concrete example, and which are real alternatives?"],
            ["Claim 5 adds an unrelated detail through a long chain.", "Reconsider the parent and preserve sibling breadth.", "Which inherited limitations are actually needed?"],
            ["The model significantly outperforms others.", "State the measured metric, comparator, and conditions.", "Was significance statistically established or merely descriptive?"],
          ],
        },
      },
      {
        id: "claim-tree-snapshot",
        title: "Claim-tree snapshot",
        label: "Quick reference",
        table: {
          caption: "Dependency choices",
          headers: ["Situation", "Likely structure"],
          rows: [
            ["Alternative sensor species", "Sibling dependents from the same broader parent"],
            ["Verification followed by mismatch alert", "A chain because the alert depends on verification"],
            ["Broad relationship followed by implementation details", "A broad-to-specific ladder"],
            ["Different commercially valuable claim boundary", "Consider a separate independent root"],
            ["Allowable child beneath a rejected parent", "Compare promotion, independent rewriting, and branch preservation"],
          ],
        },
      },
      {
        id: "source-hierarchy",
        title: "Know what kind of guidance you are using",
        label: "Caution",
        table: {
          caption: "Authority and judgment",
          headers: ["Type", "Use"],
          rows: [
            ["Statute", "Start with the governing legal text."],
            ["USPTO guidance", "Understand current examination procedure and examples."],
            ["Firm or practitioner practice", "Apply drafting style and strategy appropriate to the matter."],
            ["Training example", "Practice a technique without treating the example as a legal rule."],
          ],
        },
        callout: {
          tone: "caution",
          title: "Confirm current authority",
          text: "Rules, fees, examination practice, and controlling law can change. Verify current official sources and the actual record before relying on a training guide.",
        },
      },
    ],
    checklist: [
      "I can state the invention's technical mechanism in one sentence.",
      "I can trace input → operation → result → feedback.",
      "The claim boundary and actors are clear.",
      "Important nouns are connected by explicit relationships.",
      "Data and states have stable identities.",
      "Causation and necessary timing are stated.",
      "Dependent claims create meaningful fallbacks rather than filler.",
      "The Summary mirrors the claim architecture without copying claim fragments.",
      "Figure narratives explain relationships and operation, not only components.",
      "Optionality is deliberate and section-appropriate.",
      "Reported results remain tied to their actual metric and conditions.",
      "The complete claim set and specification have been checked for support and consistency.",
    ],
    sources: sources("usc112", "utilityGuide", "mpep608", "mpep707", "mpep2163", "mpep2173"),
    related: ["application-workflow", "independent-claims", "dependent-claims", "drafting-language"],
  },
];

export function getGuideBySlug(slug) {
  return guides.find((guide) => guide.slug === slug) ?? null;
}

export function guideHref(slug, sectionId) {
  const base = `/guides/${encodeURIComponent(slug)}`;
  return sectionId ? `${base}#${encodeURIComponent(sectionId)}` : base;
}
